// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT2IKA56ovQL1Snagsdd7xZt6d9uIXC_I',
    appId: '1:12785480038:web:6c4ba3b6754b2db7c458a7',
    messagingSenderId: '12785480038',
    projectId: 'campus-navigation-app-27865',
    authDomain: 'campus-navigation-app-27865.firebaseapp.com',
    storageBucket: 'campus-navigation-app-27865.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuGrJULQQuqpl4_uczlfOz6_R-kVoHGdY',
    appId: '1:12785480038:android:c43a99390a4387eac458a7',
    messagingSenderId: '12785480038',
    projectId: 'campus-navigation-app-27865',
    storageBucket: 'campus-navigation-app-27865.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDleZSET04ZzMo3xgk-hV2Mx58_82hHvUQ',
    appId: '1:12785480038:ios:141ccf57fdedb1e6c458a7',
    messagingSenderId: '12785480038',
    projectId: 'campus-navigation-app-27865',
    storageBucket: 'campus-navigation-app-27865.firebasestorage.app',
    iosBundleId: 'com.example.campusNavigationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDleZSET04ZzMo3xgk-hV2Mx58_82hHvUQ',
    appId: '1:12785480038:ios:141ccf57fdedb1e6c458a7',
    messagingSenderId: '12785480038',
    projectId: 'campus-navigation-app-27865',
    storageBucket: 'campus-navigation-app-27865.firebasestorage.app',
    iosBundleId: 'com.example.campusNavigationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT2IKA56ovQL1Snagsdd7xZt6d9uIXC_I',
    appId: '1:12785480038:web:09d3c0f422571179c458a7',
    messagingSenderId: '12785480038',
    projectId: 'campus-navigation-app-27865',
    authDomain: 'campus-navigation-app-27865.firebaseapp.com',
    storageBucket: 'campus-navigation-app-27865.firebasestorage.app',
  );

}